# name: CI-CD Pipeline

# on:
#   workflow_dispatch:
#   push:
#     # branches:
#     #   - main
#     # paths:
#     #   - .github/workflows/main.yml
#   pull_request:
#     branches:
#       - main

# jobs:
#   # Start of build job: Build the web application
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4.1.5

#       - name: Set up JDK 11
#         uses: actions/setup-java@v2
#         with:
#           java-version: '11'
#           distribution: 'adopt' # Specify distribution

#       - name: Set up Node.js
#         uses: actions/setup-node@v4.0.2
#         with:
#           node-version: '12'

#   # Start of test job: Test that the web application is up to standard
#   test: 
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v4.0.2
#         with:
#           node-version: '12'

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests on HTML files
#         run: |
#           # Example: Validate HTML file
#           npx htmlhint src

#   # Start of scan job: Scan the code for any vulnerabilities or known CSV
#   scan:
#     runs-on: ubuntu-latest
#     needs: [test,build]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: SonarCloud Scan
#         uses: ./.github/template/sonarcloud/
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#       - name: Scan HTML file for vulnerabilities
#         run: |
#           # Example: Scan for security issues using a tool like retire.js
#           npx retire --path src/test.html --outputformat json

#   # Start of deploy job: Deploy code via docker to Kubernetes
#   deploy:
#     needs: [test,build,scan]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4.1.5

#       - name: Setup kubectl
#         uses: azure/setup-kubectl@v1
#         with:
#           version: v1.18.15

#       - name: Docker Deploy
#         uses: ./.github/template/docker/
#         with:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Needed to get PR information, if any
#           DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
